# create a conda environment with: `conda env create`
name: synchro
channels:
- defaults
- conda-forge
dependencies:
- python
- nb_conda_kernels
- numpy
- pandas
- xlrd
- xgboost
- seaborn
- shap
- altair
- pymc3
- platypus-opt
